sudo: false

language: r
r:
  - oldrel
  - release
  - devel

cache: packages

before_install:
  - Rscript -e 'install.packages("knitr")'
  - cd ArboristBridgeR/Package/
  - chmod u+x Rborist.travis.sh
  - ./Rborist.travis.sh

install:
  - tar -xzvf Rborist_*.*-*.tar.gz
  - Rscript -e 'install.packages("rmarkdown")'
  - Rscript -e 'install.packages("roxygen2")'
  - Rscript -e 'install.packages("devtools")'
  - Rscript -e 'devtools::install_deps("Rborist", dependencies = T)'
script:
  - Rscript -e 'devtools::check("Rborist", manual = FALSE)'
  
notifications:
  email:
    on_success: change
    on_failure: change

r_github_packages:
  - jimhester/covr

# This can be enabled if you want code coverage
#after_success:
#  - Rscript -e 'install.packages("covr"); covr::coveralls("Rborist")'
