language: r
cache: packages
sudo: required
warnings_are_errors: true

addons:
  apt:
    sources: ['ubuntu-toolchain-r-test']
    packages: ['g++-6','libgit2-dev']

env:
  - COMPILER=g++-6

r:
  - devel
  - oldrel
  - release

before_install:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 100
  - Rscript -e 'install.packages("knitr")'
  - cd Rborist/Package/
  - chmod u+x Rborist.travis.sh
   
install:
  - ./Rborist.travis.sh
  - tar -xzvf Rborist_*.*-*.tar.gz
  - Rscript -e 'install.packages("rmarkdown")'
  - Rscript -e 'install.packages("roxygen2")'
  - Rscript -e 'install.packages("devtools")'
  - Rscript -e 'devtools::install_deps("Rborist", dependencies = T)'
  
script:
  - Rscript -e 'devtools::check("Rborist", manual = FALSE)'
  
notifications:
  email:
    on_success: change
    on_failure: change

r_github_packages:
  - jimhester/covr

# This can be enabled if you want code coverage
#after_success:
#  - Rscript -e 'install.packages("covr"); covr::coveralls("Rborist")'
